### ISSUE TITLE
Restructure the organization of the folders?

### ISSUE THREAD

**Issue by likanzhan** [greimel/pluto-course-template#10]
Thank you guys very much for your excellent work!  
I'm just wondering whether is it reasonable and possible to

(1) move `_layout` from `website` to `generate`, 
(2) combine `_css` in `website` with `css` in `generate`, 
(3) move `assets` into the root directory, and 
(4) rename `website` to `markdowns` or something,  

so that

`notebooks`, `markdowns`, and `assets` contain only user provided information, and 
all the `setup` information are stored in `generate` folder?

Thank you guys again.

**Comment by greimel** [comment]
That's a very good idea!

The reason why it's done that way is that the markdown pages are rendered by Franklin.jl (that's where the `website/_css` and `website/_layout` are needed) and the sidebar is styled by `generate/css`.

I don't know if one can tell Franklin to look for the `_css` and `_layout` elsewhere. If not one could manually copy files from the user specified folders to some internal folder.

A PR is welcome :-)

**Comment by greimel** [comment]
We use a different folder structure now, so this is obsolete.
