### ISSUE TITLE
Rename `website` and `newwebsite` to something more clear?

### ISSUE THREAD

**Issue by fonsp** [greimel/pluto-course-template#8]

**Comment by greimel** [comment]
I've not done that yet so as not to lose the diffs wrt to the state of your PR.

But I thought about `newwebsite/` =>  `generate/`. Do you have better ideas?

**Comment by fonsp** [comment]
Nice, let's do that! Should I also update the PR?

**Comment by greimel** [comment]
Alright! 

I'd suggest that you squash the last two commits of you PR (those that generate `newwebsite`), rename the folder, and then do `git commit --amend`. 

Then I can rebase against your branch and there should always be nice diffs.

**Comment by fonsp** [comment]
I don't know how to do those things! 😅 But I will ask a friend to help me tomorrow :)

**Comment by greimel** [comment]
I hope I am not being too pedantic 🙈

**Comment by fonsp** [comment]
done!

**Comment by greimel** [comment]
done!
